repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: debug-statements
- repo: https://github.com/psf/black
  rev: 23.10.1
  hooks:
    - id: black
      # It is recommended to specify the latest version of Python
      # supported by your project here, or alternatively use
      # pre-commit's default_language_version, see
      # https://pre-commit.com/#top_level-default_language_version
      language_version: python3.11
- repo: https://github.com/python-poetry/poetry
  rev: '1.5.1'
  hooks:
    - id: poetry-check
      args: ["--directory", "backend"]
    - id: poetry-lock
      args: ["--directory", "backend"]
    - id: poetry-export
      args: ["-f", "requirements.txt", "-o", "backend/requirements.txt", "--directory", "backend", "--with", "dev"]
